### ISSUE TITLE
Make attendance component

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#10]
- Replace this card from dashboard: 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/45785817/94835786-c29d6100-042f-11eb-960a-f7d432e2d72a.png">

- Make disk/circular progress of attendance in this card

**Comment by manan2501** [comment]
Will this do?
![image](https://user-images.githubusercontent.com/43081866/94953909-ecc15280-0505-11eb-8f83-d86e118c823b.png)

**Comment by manan2501** [comment]
I am working on this, so can you please assign this to me? so that there are no conflicts in the future.
