### ISSUE TITLE
[Dashboard] Recently accessed documents

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#11]
- Update this card to show the list of recently accessed documents
<img width="775" alt="image" src="https://user-images.githubusercontent.com/45785817/94836074-27f15200-0430-11eb-8e23-ef67c8485fc9.png">

- Recently accessed documents
- You're required to make a React component for this task

**Comment by Aniruddhmuley2001** [comment]
@meet59patel @HemangNakarani Does this require to change the table headings and add some dummy doc file name instead of .html files?

**Comment by meet59patel** [comment]
@Aniruddhmuley2001 earlier we had different plans with this component. But now we've decided to show **recently accessed files** list in here. 

- Shows `Filename` (on click will open the file) and `last access time` of the file 
- you can remove other fields 
- **Important** :  Currently this table is made directly inside `views/Index.js`, but make the new component (reusing the code) and save component to `components/dashboard/RecentlyAccessed.js` , and import this component inside `views/Index.js`
- Make sure the data that's shown inside the table comes from a variable (array) something like this:
```
let recentlyAccessed = [ {
    fileName: 'filename',
    lastAccessed: "Mon, 05 Oct 2020 16:11:10 GMT"
}, more objects in the array... ];
```

- I'll be requiring data implementation part in this way so that we can use the same attributes while making database schema and incorporating fetching from DB becomes very easy.

**Comment by Aniruddhmuley2001** [comment]
@meet59patel @HemangNakarani I would like to work on this issue.
