### ISSUE TITLE
[Dashboard] Show online friends list

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#12]
- Change this card to incorporate this change 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/45785817/94836765-fb8a0580-0430-11eb-926e-5e1287e98591.png">

- This card should a show currently online friends list with a green dot on side
- You're required to make a React component for this task

**Comment by Aniruddhmuley2001** [comment]
@meet59patel I would like to work on this issue.

**Comment by Aniruddhmuley2001** [comment]
@meet59patel Also, can we have 3 columns namely, Photo, Name and Status(Online/Offline with green dot)? This can make it more readable, and independent of the image background, in case we think of adopting the way the status is shown in social media applications

**Comment by meet59patel** [comment]
@Aniruddhmuley2001 that's a good idea. Go ahead with Photo, Name and Status like you mentioned.
