### ISSUE TITLE
[Documentation] Add contributions guidelines and Issue templates

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#14]
## Contributing guidelines
- Should list out all the rules shared by @meet59patel in the gitter chat
- Think for more rules if necessary
- All of these contribution guidelines to be saved as `CONTRIBUTING.md`
- For reference: [Reference 1](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md), [Reference 2](https://github.com/harsh-2711/getting-started/blob/master/CONTRIBUTING.md)
- Also add little git guide like this: 
<img width="632" alt="image" src="https://user-images.githubusercontent.com/45785817/94844664-36de0180-043c-11eb-8bef-2e6b48914407.png">

******
## Issue Templates
- All the documentation must be in `Markdown` format
- Issue templates for
  - Bug report
  - Feature request
- One issue template for example: 
![image](https://user-images.githubusercontent.com/45785817/94839948-50c81600-0435-11eb-8f36-21d82ddd7dee.png)

**Comment by godslayer201** [comment]
I would like to work on this issue

**Comment by meet59patel** [comment]
Go ahead @godslayer201 👍🏻
