### ISSUE TITLE
[Top Navbar] Change the user name dynamically

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#24]
- Get the value of Name and User's profile picture URL from Google Authentication response
- Set the name and image here: (accessible from `AdminNavbar.js`)
<img width="247" alt="image" src="https://user-images.githubusercontent.com/45785817/95133071-55b2ff80-077e-11eb-9145-2a820a88be83.png">

- Need to use React Context to implement this
- Look for `UserProvider` inside `src/context/UserContext.js`
- Set a new `name` attribute and `profileImage` that stores image URL

**Comment by 201801057** [comment]
@meet59patel can I work on this issue ?

**Comment by Aniruddhmuley2001** [comment]
@meet59patel would like to work on this issue.
