### ISSUE TITLE
Update favicon & <meta> tags

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#5]
- [ ] Update `favicon.ico`

- [ ] Add `<meta>` tags if needed (research and suggest) - For reference, check: [HTML Head Boilerplate & Reference](https://gist.github.com/nunosans/3028849)

**Comment by Aniruddhmuley2001** [comment]
@meet59patel In the first issue, the react logo has to be replaced by the project logo in favicon.ico, right?

**Comment by Aniruddhmuley2001** [comment]
Also, I would like to work on this issue!

**Comment by meet59patel** [comment]
@Aniruddhmuley2001 Yes 

> @meet59patel In the first issue, the react logo has to be replaced by the project logo in favicon.ico, right?

Yes you're right. 

But looks like @helloshantanu made a PR already resolving this issue. I'll be opening many more issues by tonight and take a look from them.

**Comment by Aniruddhmuley2001** [comment]
@meet59patel Ok, sure!
