### ISSUE TITLE
Update Menu (Sidebar)

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#7]
### These NavLinks should be there
- [ ] Dashboard
- [ ] Time table (Here goes Calendar as well)
- [ ] Schedule
- [ ] Attendance
- [ ] Assignments
- [ ] Storage
- [ ] Grades
- [ ] Reminders
- [ ] Quick Notes

In place of these links: 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/45785817/94834822-83badb80-042e-11eb-8997-0b1941e48543.png">

**Comment by Aniruddhmuley2001** [comment]
@meet59patel I would like to work on this issue

**Comment by manan2501** [comment]
I would like to work on this one. Can you please assign it to me?

**Comment by manan2501** [comment]
https://manan2501-schooler.vercel.app/admin/index

**Comment by HemangNakarani** [comment]
give @manan2501 5 points
