### ISSUE TITLE
Remove Sidebar documentation links

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#8]
#### Remove these links from sidebar: 
<img width="228" alt="image" src="https://user-images.githubusercontent.com/45785817/94834583-2aeb4300-042e-11eb-8f8d-c7c6f61a43db.png">

- Add GitHub Repository link here with Github icon

**Comment by priyanshk20** [comment]
I want to take up this issue

**Comment by meet59patel** [comment]
Sure. Go ahead @priyanshk20
