### ISSUE TITLE
Update dashboard small cards at top

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler#9]
Think and discuss about this before finalizing titles to these fields

- [ ] Keep the predefined cards structure but it'll have information like "No assignments due", "No Submissions due" etc.

- These cards are being referred here: 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/45785817/94835972-085a2980-0430-11eb-911c-ebb72065303e.png">

**Comment by Aniruddhmuley2001** [comment]
@meet59patel Does the issue only require parameters to be included for now, or the whole setup of it to be ready?

**Comment by Aniruddhmuley2001** [comment]
If only parameters are to be decided, I would love to work on this issue, given limited work is done till now. Later they can be integrated when at the setup gets ready.

**Comment by HemangNakarani** [comment]
@Aniruddhmuley2001 You will have to design an appropriate card component to display details like

- Assignment Title
- Course name
- Instructors Name
- Due date
- Course Icon

And Replace this card here, for now just make this 4 copies only. We will have Horizontal ScrollView Later on.

You can input your ideas also. You can add more relevant details fields in your way.
